name: sky_high_jumper
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.7.0
  auto_route: ^8.1.3
  intl: ^0.19.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10

flutter:
  generate: true
  uses-material-design: true
